name: Release assets

on:
  release:
    types:
      - prereleased
      - released

env:
  BUILD_DIR: "cmake-build-release"

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      build_dir: ${{ env.BUILD_DIR }}
    steps:
      - run: echo "Exposing env vars"

  build-release:
    needs: vars
    uses: stolex1y/load-balancer/.github/workflows/build.yml@master
    with:
      build_type: "Release"
      build_dir: ${{ needs.vars.outputs.build_dir }}

  upload-assets:
    runs-on: ubuntu-latest
    needs: [ vars, build-release ]
    permissions:
      contents: write
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.vars.outputs.build_dir }}
          path: .

      - name: Extract build archive
        run: |
          tar -xzf "$BUILD_DIR.tar.gz"
          sudo chmod -R 755 $BUILD_DIR

      - name: Update release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ github.event.release.body }}
          draft: ${{ github.event.release.draft }}
          name: ${{ github.event.release.name }}
          prerelease: ${{ github.event.release.prerelease }}
          tag: ${{ github.event.release.tag_name }}
          artifacts: "${{ needs.vars.outputs.build_dir }}/*.tar.gz"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
